//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardGame.DAL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class itin21_ClonestoneFSEntities : DbContext
    {
        public itin21_ClonestoneFSEntities()
            : base("name=itin21_ClonestoneFSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Card> AllCards { get; set; }
        public virtual DbSet<CardClass> AllCardClasses { get; set; }
        public virtual DbSet<UserCardCollection> AllUserCardCollections { get; set; }
        public virtual DbSet<Deck> AllDecks { get; set; }
        public virtual DbSet<DeckCard> AllDeckCards { get; set; }
        public virtual DbSet<Purchase> AllPurchases { get; set; }
        public virtual DbSet<Pack> AllPacks { get; set; }
        public virtual DbSet<User> AllUsers { get; set; }
        public virtual DbSet<CardType> AllCardTypes { get; set; }
    }
}
