//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardGame.DAL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class itin21_ClonestoneFSEntities : DbContext
    {
        public itin21_ClonestoneFSEntities()
            : base("name=itin21_ClonestoneFSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Card> AllCards { get; set; }
        public virtual DbSet<CardClass> AllCardClasses { get; set; }
        public virtual DbSet<UserCardCollection> AllUserCardCollections { get; set; }
        public virtual DbSet<Deck> AllDecks { get; set; }
        public virtual DbSet<DeckCard> AllDeckCards { get; set; }
        public virtual DbSet<Purchase> AllPurchases { get; set; }
        public virtual DbSet<Pack> AllPacks { get; set; }
        public virtual DbSet<User> AllUsers { get; set; }
        public virtual DbSet<CardType> AllCardTypes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    
        public virtual ObjectResult<pGetSellingstatsDay_Result> pGetSellingstatsDay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pGetSellingstatsDay_Result>("pGetSellingstatsDay");
        }
    
        public virtual ObjectResult<pGetSellingstatsMonth_Result> pGetSellingstatsMonth()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pGetSellingstatsMonth_Result>("pGetSellingstatsMonth");
        }
    
        public virtual ObjectResult<pGetUserSignUpsWeek_Result> pGetUserSignUpsWeek()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pGetUserSignUpsWeek_Result>("pGetUserSignUpsWeek");
        }
    
        public virtual int pGetTop10Sellers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pGetTop10Sellers");
        }
    
        public virtual ObjectResult<pGetSellingGainsTwoWeeks_Result> pGetSellingGainsTwoWeeks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pGetSellingGainsTwoWeeks_Result>("pGetSellingGainsTwoWeeks");
        }
    
        public virtual ObjectResult<pGetSellingOverallTwoWeeks_Result> pGetSellingOverallTwoWeeks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pGetSellingOverallTwoWeeks_Result>("pGetSellingOverallTwoWeeks");
        }
    
        public virtual ObjectResult<pGetSellingWholeOrdersLastTwoWeeks_Result> pGetSellingWholeOrdersLastTwoWeeks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pGetSellingWholeOrdersLastTwoWeeks_Result>("pGetSellingWholeOrdersLastTwoWeeks");
        }
    
        public virtual ObjectResult<pGetSignUpsWeek_Result> pGetSignUpsWeek()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pGetSignUpsWeek_Result>("pGetSignUpsWeek");
        }
    
        public virtual ObjectResult<pGetCountSignUpsWeek_Result> pGetCountSignUpsWeek()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pGetCountSignUpsWeek_Result>("pGetCountSignUpsWeek");
        }
    
        public virtual ObjectResult<pGetSellingstatsLast24hours_Result> pGetSellingstatsLast24hours()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pGetSellingstatsLast24hours_Result>("pGetSellingstatsLast24hours");
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<pGetTop10Buyers_Result> pGetTop10Buyers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pGetTop10Buyers_Result>("pGetTop10Buyers");
        }
    }
}
