//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardGame.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Card()
        {
            this.AllUserCardCollection = new HashSet<UserCardCollection>();
            this.AllDeckCards = new HashSet<DeckCard>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public byte ManaCost { get; set; }
        public short Life { get; set; }
        public short Attack { get; set; }
        public string FlavorText { get; set; }
        public int ID_CardType { get; set; }
        public Nullable<int> ID_CardClass { get; set; }
        public byte[] Image { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ImageMimeType { get; set; }
    
        public virtual CardClass CardClass { get; set; }
        public virtual CardType CardType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCardCollection> AllUserCardCollection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeckCard> AllDeckCards { get; set; }
    }
}
