//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardGame.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcollection
    {
        public int idcollection { get; set; }
        public Nullable<int> fkperson { get; set; }
        public Nullable<int> numcards { get; set; }
        public int fkcard { get; set; }
    
        public virtual tblcard tblcard { get; set; }
        public virtual tblperson tblperson { get; set; }
    }
}
