//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardGame.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationLabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardGame.Resources.ValidationLabels", typeof(ValidationLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack.
        /// </summary>
        public static string ATTACK {
            get {
                return ResourceManager.GetString("ATTACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sperrdatum.
        /// </summary>
        public static string BANDATE {
            get {
                return ResourceManager.GetString("BANDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreditkartenfirma.
        /// </summary>
        public static string CARD_COMPANY {
            get {
                return ResourceManager.GetString("CARD_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ablaufdatum.
        /// </summary>
        public static string CARD_EXPIRY {
            get {
                return ResourceManager.GetString("CARD_EXPIRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kartenbesitzer.
        /// </summary>
        public static string CARD_HOLDER {
            get {
                return ResourceManager.GetString("CARD_HOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name der Karte.
        /// </summary>
        public static string CARD_NAME {
            get {
                return ResourceManager.GetString("CARD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kartennummer.
        /// </summary>
        public static string CARD_NUMBER {
            get {
                return ResourceManager.GetString("CARD_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sicherheitscode.
        /// </summary>
        public static string CARD_SECURITY_N {
            get {
                return ResourceManager.GetString("CARD_SECURITY_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kartenklasse.
        /// </summary>
        public static string CLASS {
            get {
                return ResourceManager.GetString("CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort bestätigen.
        /// </summary>
        public static string CONFIRMATION {
            get {
                return ResourceManager.GetString("CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontostand.
        /// </summary>
        public static string CURRENCYBALANCE {
            get {
                return ResourceManager.GetString("CURRENCYBALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string DATE {
            get {
                return ResourceManager.GetString("DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        public static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emailadresse.
        /// </summary>
        public static string EMAIL_LABEL {
            get {
                return ResourceManager.GetString("EMAIL_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        public static string FIRSTNAME {
            get {
                return ResourceManager.GetString("FIRSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spitzname.
        /// </summary>
        public static string GAMERTAG {
            get {
                return ResourceManager.GetString("GAMERTAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild.
        /// </summary>
        public static string IMAGE {
            get {
                return ResourceManager.GetString("IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiv(Hacken für gelöscht).
        /// </summary>
        public static string ISACTIVE {
            get {
                return ResourceManager.GetString("ISACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelöscht.
        /// </summary>
        public static string ISDELETED {
            get {
                return ResourceManager.GetString("ISDELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ist ein COIN-Packet?.
        /// </summary>
        public static string ISMONEY {
            get {
                return ResourceManager.GetString("ISMONEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname.
        /// </summary>
        public static string LASTNAME {
            get {
                return ResourceManager.GetString("LASTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life.
        /// </summary>
        public static string LIFE {
            get {
                return ResourceManager.GetString("LIFE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mana.
        /// </summary>
        public static string MANA_COST {
            get {
                return ResourceManager.GetString("MANA_COST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl.
        /// </summary>
        public static string NUMBER {
            get {
                return ResourceManager.GetString("NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karten-Anzahl.
        /// </summary>
        public static string NUMBER_CARDS {
            get {
                return ResourceManager.GetString("NUMBER_CARDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl/Packs.
        /// </summary>
        public static string NUMBER_PACKAGES {
            get {
                return ResourceManager.GetString("NUMBER_PACKAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        public static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preis.
        /// </summary>
        public static string PRICE {
            get {
                return ResourceManager.GetString("PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PRODUCT_NAME {
            get {
                return ResourceManager.GetString("PRODUCT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrierungsdatum.
        /// </summary>
        public static string SIGN_IN_DATE {
            get {
                return ResourceManager.GetString("SIGN_IN_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habe die Agb´s durchgelesen und akzeptiere sie.
        /// </summary>
        public static string TERMS_ACCEPT {
            get {
                return ResourceManager.GetString("TERMS_ACCEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string TEXT {
            get {
                return ResourceManager.GetString("TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summe.
        /// </summary>
        public static string TOTAL_COST {
            get {
                return ResourceManager.GetString("TOTAL_COST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kartentyp.
        /// </summary>
        public static string TYPE {
            get {
                return ResourceManager.GetString("TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolle.
        /// </summary>
        public static string USERROLE {
            get {
                return ResourceManager.GetString("USERROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wert.
        /// </summary>
        public static string WORTH {
            get {
                return ResourceManager.GetString("WORTH", resourceCulture);
            }
        }
    }
}
