//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardGame_v2.DAL.EDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CardGame_v2Entities : DbContext
    {
        public CardGame_v2Entities()
            : base("name=CardGame_v2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCard> tblCard { get; set; }
        public virtual DbSet<tblCardPack> tblCardPack { get; set; }
        public virtual DbSet<tblCardType> tblCardType { get; set; }
        public virtual DbSet<tblDeck> tblDeck { get; set; }
        public virtual DbSet<tblDeckCard> tblDeckCard { get; set; }
        public virtual DbSet<tblUserCardCollection> tblUserCardCollection { get; set; }
        public virtual DbSet<tblUserRole> tblUserRole { get; set; }
        public virtual DbSet<tblVirtualPurchase> tblVirtualPurchase { get; set; }
        public virtual DbSet<tblUser> tblUser { get; set; }
    }
}
