//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardGame_v2.DAL.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserCardCollection
    {
        public int fkUser { get; set; }
        public int fkCard { get; set; }
        public int numcards { get; set; }
    
        public virtual tblCard tblCard { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
