//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardGame.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbldeckcard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbldeckcard()
        {
            this.tblcollection = new HashSet<tblcollection>();
        }
    
        public int iddeckcard { get; set; }
        public int fkdeck { get; set; }
        public int fkcard { get; set; }
        public Nullable<int> numcards { get; set; }
    
        public virtual tblcard tblcard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblcollection> tblcollection { get; set; }
        public virtual tbldeck tbldeck { get; set; }
    }
}
