//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardGame.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblorder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblorder()
        {
            this.tblcollection = new HashSet<tblcollection>();
        }
    
        public int idorder { get; set; }
        public Nullable<System.DateTime> orderdate { get; set; }
        public Nullable<int> fkperson { get; set; }
        public Nullable<int> fkpack { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblcollection> tblcollection { get; set; }
        public virtual tblpack tblpack { get; set; }
        public virtual tblperson tblperson { get; set; }
    }
}
