//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardGame.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpack
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblpack()
        {
            this.tblorder = new HashSet<tblorder>();
        }
    
        public int idpack { get; set; }
        public string packname { get; set; }
        public Nullable<decimal> packprice { get; set; }
        public Nullable<int> cardquantity { get; set; }
        public byte[] packimage { get; set; }
        public string flavour { get; set; }
        public Nullable<bool> ismoney { get; set; }
        public Nullable<int> numcards { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblorder> tblorder { get; set; }
    }
}
