//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardGame.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblperson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblperson()
        {
            this.tblcollection = new HashSet<tblcollection>();
            this.tbldeck = new HashSet<tbldeck>();
            this.tblorder = new HashSet<tblorder>();
        }
    
        public int idperson { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string gamertag { get; set; }
        public Nullable<int> currencybalance { get; set; }
        public Nullable<bool> isactive { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string salt { get; set; }
        public string userrole { get; set; }
        public byte[] pic { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblcollection> tblcollection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbldeck> tbldeck { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblorder> tblorder { get; set; }
    }
}
